[package]
name = "fastladder-pixiv"
version = "0.1.0"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]

[dependencies]
chrono = "0.2"
clap = "2.19"
cookie = "0.2"
env_logger = "0.3"
hyper = "0.9"
lazy_static = "0.2"
log = "0.3"
regex = "0.2"
rustc-serialize = "0.3"
select = "0.3"
url = "1.2"
